function main() {
    let a: number = 10;
    let b: number = 3;
    let add: number = a + b;
    let sub: number = a - b;
    let mul: number = a * b;
    let div: number = a / b;
    let mod: number = a % b;
    console.log("加法: " + String(add));
    console.log("减法: " + String(sub));
    console.log("乘法: " + String(mul));
    console.log("除法: " + String(div));
    console.log("取模: " + String(mod));
    let eq: boolean = a === 10;
    let ne: boolean = a !== 5;
    let lt: boolean = a < 20;
    let gt: boolean = a > 0;
    let le: boolean = a <= 10;
    let ge: boolean = a >= 10;
    console.log("等于: " + String(Boolean(eq)));
    console.log("不等于: " + String(Boolean(ne)));
    console.log("小于: " + String(Boolean(lt)));
    console.log("大于: " + String(Boolean(gt)));
    let and: number = a & b;
    let or: number = a | b;
    let xor: number = a ^ b;
    let notBits: number = ~a;
    let shl: number = a << 2;
    let shr: number = a >> 1;
    console.log("位与: " + String(and));
    console.log("位或: " + String(or));
    console.log("位异或: " + String(xor));
    console.log("位取反: " + String(notBits));
    console.log("左移: " + String(shl));
    console.log("右移: " + String(shr));
    let and2: boolean = (a > 0) && (b > 0);
    let or2: boolean = (a > 100) || (b < 10);
    let not2: boolean = !(a > 100);
    console.log("逻辑与: " + String(Boolean(and2)));
    console.log("逻辑或: " + String(Boolean(or2)));
    console.log("逻辑非: " + String(Boolean(not2)));
    let x: number = 5;
    let preInc: number = ++x;
    let postInc: number = x++;
    let preDec: number = --x;
    let postDec: number = x--;
    console.log("前缀++: " + String(preInc));
    console.log("后缀++: " + String(postInc));
    console.log("前缀--: " + String(preDec));
    console.log("后缀--: " + String(postDec));
    let y: number = 10;
    y += 5;
    console.log("+= : " + String(y));
    y -= 3;
    console.log("-= : " + String(y));
    y *= 2;
    console.log("*= : " + String(y));
    y /= 4;
    console.log("/= : " + String(y));
    y %= 5;
    console.log("%= : " + String(y));
    let max: number = a > b ? a : b;
    console.log("max = " + String(max));
}
main();