import { Program } from '../parser/ast';
import { Transformer } from '../transformer/index';

/**
 * 代码生成器 — 将 Collie AST 转换为 TypeScript 源代码
 *
 * 封装 Transformer，添加运行时代码和文件头。
 */
export class CodeGenerator {
    private transformer: Transformer;

    constructor() {
        this.transformer = new Transformer();
    }

    /**
     * 生成 TypeScript 代码
     */
    generate(program: Program): string {
        const body = this.transformer.transform(program);

        const header = [
            '// Auto-generated by Collie DSL Compiler',
            '// Source: ' + (program.span?.start?.offset !== undefined
                ? `offset ${program.span.start.offset}`
                : 'unknown'),
            '',
            body,
        ];

        return header.join('\n');
    }

    /**
     * 仅生成转换后的代码(不含头部注释)
     */
    generateCodeOnly(program: Program): string {
        return this.transformer.transform(program);
    }
}
